import { Product, Category } from "./schema";

export const initialCategories: Category[] = [
  {
    id: 1,
    name: "Haute Horlogerie",
    slug: "timepieces",
    description: "Swiss precision craftsmanship meets architectural minimalism.",
    image: "https://images.unsplash.com/photo-1524805444758-089113d48a6d?q=80&w=900&auto=format&fit=crop",
    createdAt: new Date(),
  },
  {
    id: 2,
    name: "Bespoke Leather",
    slug: "leather-goods",
    description: "Hand-stitched full grain Tuscan leather carryalls and accessories.",
    image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=900&auto=format&fit=crop",
    createdAt: new Date(),
  },
  {
    id: 3,
    name: "Rare Perfumery",
    slug: "fragrance",
    description: "Artisanal extrait de parfum distilled in Grasse, France.",
    image: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?q=80&w=900&auto=format&fit=crop",
    createdAt: new Date(),
  },
  {
    id: 4,
    name: "Fine Silk Atelier",
    slug: "apparel",
    description: "Mulberry silk robes, structured blazers, and evening tailoring.",
    image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=900&auto=format&fit=crop",
    createdAt: new Date(),
  },
];

export const initialProducts: Product[] = [
  {
    id: 1,
    name: "Chronographe Royal Obsidian",
    slug: "chronographe-royal-obsidian",
    tagline: "Limited Edition / 100 Pieces",
    description: "Engineered with a skeletonized automatic tourbillon movement encased in DLC-treated aerospace titanium and anti-reflective sapphire crystal. Hand-finished with an alligator strap.",
    price: 3450,
    compareAtPrice: 3800,
    categorySlug: "timepieces",
    featured: true,
    stock: 7,
    rating: 4.95,
    reviewsCount: 38,
    image: "https://images.unsplash.com/photo-1524805444758-089113d48a6d?q=80&w=900&auto=format&fit=crop",
    gallery: JSON.stringify([
      "https://images.unsplash.com/photo-1524805444758-089113d48a6d?q=80&w=900&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=900&auto=format&fit=crop",
    ]),
    tags: "Limited Edition,Horology,Titanium",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    name: "Atelier Weekender in Cognac Calfskin",
    slug: "atelier-weekender-cognac",
    tagline: "Vegetable-Tanned Tuscan Leather",
    description: "Crafted from hand-selected full-grain Italian leather that ages into a rich patina. Accented with solid brushed brass hardware, waterproof canvas lining, and a dedicated footwear compartment.",
    price: 1280,
    compareAtPrice: 1450,
    categorySlug: "leather-goods",
    featured: true,
    stock: 14,
    rating: 4.92,
    reviewsCount: 64,
    image: "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?q=80&w=900&auto=format&fit=crop",
    gallery: JSON.stringify([
      "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?q=80&w=900&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=900&auto=format&fit=crop",
    ]),
    tags: "Handcrafted,Tuscan Leather,Travel",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    name: "Santal & Ambre Doré Extrait",
    slug: "santal-ambre-dore-extrait",
    tagline: "100ml / 3.4 fl oz Pure Extrait",
    description: "A decadent nocturnal blend of wild aged Mysore sandalwood, smoky amber resin, Sicilian bergamot, and velvet iris. Hand-numbered flacon capped in magnetic polished brass.",
    price: 420,
    compareAtPrice: null,
    categorySlug: "fragrance",
    featured: true,
    stock: 22,
    rating: 4.98,
    reviewsCount: 112,
    image: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?q=80&w=900&auto=format&fit=crop",
    gallery: JSON.stringify([
      "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?q=80&w=900&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?q=80&w=900&auto=format&fit=crop",
    ]),
    tags: "Extrait,Niche,Grasse",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    name: "Midnight Silk Smoking Jacket",
    slug: "midnight-silk-smoking-jacket",
    tagline: "100% 22-Momme Mulberry Silk",
    description: "Cut with structured shoulder roping and contrast satin shawl lapels. Designed for gala evenings or intimate salon gatherings. Features horn buttons and tailored welt pockets.",
    price: 1850,
    compareAtPrice: 2100,
    categorySlug: "apparel",
    featured: true,
    stock: 9,
    rating: 4.88,
    reviewsCount: 24,
    image: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=900&auto=format&fit=crop",
    gallery: JSON.stringify([
      "https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=900&auto=format&fit=crop",
    ]),
    tags: "Tailoring,Mulberry Silk,Evening",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5,
    name: "Cadence Minimalist Gold Cuff",
    slug: "cadence-minimalist-gold-cuff",
    tagline: "18K Solid Fairmined Yellow Gold",
    description: "Flawlessly proportioned open cuff with beveled edges and an internal satin polish. Ergonomically shaped to hug the wrist with effortless presence.",
    price: 2190,
    compareAtPrice: null,
    categorySlug: "timepieces",
    featured: false,
    stock: 5,
    rating: 5.0,
    reviewsCount: 19,
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=900&auto=format&fit=crop",
    gallery: JSON.stringify([
      "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=900&auto=format&fit=crop",
    ]),
    tags: "18K Gold,Fairmined,Minimalist",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6,
    name: "Grand Tourer Folio Briefcase",
    slug: "grand-tourer-folio-briefcase",
    tagline: "Hand-Burnished Bridle Leather",
    description: "Slim architectural silhouette with twin gussets, micro-suede device sleeves, and discreet magnetic closure. Hand-burnished by artisans in Florence.",
    price: 980,
    compareAtPrice: 1100,
    categorySlug: "leather-goods",
    featured: false,
    stock: 12,
    rating: 4.91,
    reviewsCount: 45,
    image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=900&auto=format&fit=crop",
    gallery: JSON.stringify([
      "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=900&auto=format&fit=crop",
    ]),
    tags: "Leather,Office,Craftsmanship",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
